# Generated by Django 5.1.6 on 2026-09-11 11:34

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Must run before any VectorField column is created. Added by hand:
        # `makemigrations` cannot infer that the model needs a Postgres
        # extension, so without this a fresh database (a new clone, CI, or a
        # container) fails on the first migrate with
        # 'type "vector" does not exist'.
        VectorExtension(),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('SOP', 'Standard operating procedure'), ('POLICY', 'Policy'), ('REFERENCE', 'Reference / glossary'), ('PLAYBOOK', 'Playbook')], default='SOP', max_length=16)),
                ('version', models.CharField(default='1.0', max_length=16)),
                ('owner_team', models.CharField(blank=True, max_length=64)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('source_path', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField()),
                ('checksum', models.CharField(db_index=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'knowledge_documents',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('char_count', models.PositiveIntegerField(default=0)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=512)),
                ('embedding_provider', models.CharField(db_index=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.document')),
            ],
            options={
                'db_table': 'knowledge_chunks',
                'ordering': ['document_id', 'sequence'],
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='knowledge_chunk_embedding_idx', opclasses=['vector_cosine_ops'])],
                'constraints': [models.UniqueConstraint(fields=('document', 'sequence'), name='uniq_document_chunk_sequence')],
            },
        ),
    ]
