# Generated by Django 5.1.6 on 2026-09-11 10:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistant_conversations',
                'ordering': ['-last_active_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(blank=True, max_length=32)),
                ('action', models.CharField(choices=[('ai_query', 'AI query'), ('ai_query_denied', 'AI query denied'), ('ai_query_failed', 'AI query failed'), ('conversation_created', 'Conversation created')], db_index=True, max_length=32)),
                ('query_text', models.TextField(blank=True)),
                ('answer_preview', models.TextField(blank=True)),
                ('tools_called', models.JSONField(blank=True, default=list)),
                ('order_ids_touched', models.JSONField(blank=True, default=list)),
                ('succeeded', models.BooleanField(default=True)),
                ('error_code', models.CharField(blank=True, max_length=48)),
                ('duration_ms', models.FloatField(default=0)),
                ('total_input_tokens', models.PositiveIntegerField(default=0)),
                ('total_output_tokens', models.PositiveIntegerField(default=0)),
                ('trace_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='assistant.conversation')),
            ],
            options={
                'db_table': 'assistant_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('user', 'Operator'), ('assistant', 'Assistant')], max_length=16)),
                ('content', models.TextField(blank=True)),
                ('blocks', models.JSONField(blank=True, default=list)),
                ('provider', models.CharField(blank=True, max_length=32)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('stop_reason', models.CharField(blank=True, max_length=32)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cache_read_tokens', models.PositiveIntegerField(default=0)),
                ('cache_creation_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.FloatField(default=0)),
                ('tool_iterations', models.PositiveSmallIntegerField(default=0)),
                ('trace_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.conversation')),
            ],
            options={
                'db_table': 'assistant_messages',
                'ordering': ['conversation_id', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='ToolInvocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(db_index=True, max_length=64)),
                ('arguments', models.JSONField(blank=True, default=dict)),
                ('ok', models.BooleanField(default=True)),
                ('error_code', models.CharField(blank=True, max_length=48)),
                ('duration_ms', models.FloatField(default=0)),
                ('cache_hit', models.BooleanField(default=False)),
                ('iteration', models.PositiveSmallIntegerField(default=1)),
                ('trace_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_invocations', to='assistant.conversation')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_invocations', to='assistant.message')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_invocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistant_tool_invocations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', '-last_active_at'], name='assistant_c_user_id_f42d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-created_at'], name='assistant_a_user_id_1536bb_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-created_at'], name='assistant_a_action_ac81a1_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', '-created_at'], name='assistant_m_convers_e4d26f_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('conversation', 'sequence'), name='uniq_conversation_sequence'),
        ),
        migrations.AddIndex(
            model_name='toolinvocationlog',
            index=models.Index(fields=['tool_name', '-created_at'], name='assistant_t_tool_na_b9aa02_idx'),
        ),
        migrations.AddIndex(
            model_name='toolinvocationlog',
            index=models.Index(fields=['ok', '-created_at'], name='assistant_t_ok_838fe5_idx'),
        ),
    ]
