# Generated by Django 5.1.6 on 2026-09-11 09:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('kyc_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('customer_since', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customers',
                'indexes': [models.Index(fields=['full_name'], name='customers_full_na_c4a270_idx')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_type', models.CharField(choices=[('BUY', 'Customer buying a car'), ('SELL', 'Customer selling a car')], default='BUY', max_length=8)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('DOCS_PENDING', 'Documents pending'), ('PAYMENT_PENDING', 'Payment pending'), ('PAYMENT_PARTIAL', 'Partially paid'), ('PAYMENT_COMPLETE', 'Payment complete'), ('FINANCE_IN_PROGRESS', 'Finance in progress'), ('RC_TRANSFER_PENDING', 'RC transfer pending'), ('READY_FOR_DELIVERY', 'Ready for delivery'), ('OUT_FOR_DELIVERY', 'Out for delivery'), ('DELIVERED', 'Delivered'), ('ON_HOLD', 'On hold'), ('CANCELLED', 'Cancelled'), ('REFUND_PENDING', 'Refund pending'), ('REFUNDED', 'Refunded')], db_index=True, default='CREATED', max_length=32)),
                ('channel', models.CharField(choices=[('APP', 'Mobile app'), ('WEB', 'Website'), ('HUB_WALKIN', 'Hub walk-in'), ('PARTNER', 'Partner dealer'), ('TELESALES', 'Telesales')], max_length=16)),
                ('hub', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('booking_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('finance_status', models.CharField(choices=[('NOT_APPLICABLE', 'Not applicable (self funded)'), ('APPLIED', 'Application submitted'), ('UNDER_REVIEW', 'Under review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISBURSED', 'Disbursed')], default='NOT_APPLICABLE', max_length=20)),
                ('finance_partner', models.CharField(blank=True, max_length=64)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('finance_updated_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_agent', models.CharField(blank=True, max_length=80)),
                ('hold_reason', models.CharField(blank=True, max_length=200)),
                ('cancellation_reason', models.CharField(blank=True, max_length=200)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('booked_at', models.DateTimeField()),
                ('status_changed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='operations.customer')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_SCHEDULED', 'Not scheduled'), ('SCHEDULED', 'Scheduled'), ('OUT_FOR_DELIVERY', 'Out for delivery'), ('ATTEMPT_FAILED', 'Delivery attempt failed'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='NOT_SCHEDULED', max_length=24)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('slot', models.CharField(blank=True, max_length=40)),
                ('address_line', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=64)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('logistics_partner', models.CharField(blank=True, max_length=64)),
                ('tracking_reference', models.CharField(blank=True, max_length=64)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='operations.order')),
            ],
            options={
                'verbose_name_plural': 'deliveries',
                'db_table': 'deliveries',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('make', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=60)),
                ('variant', models.CharField(blank=True, max_length=60)),
                ('year', models.PositiveSmallIntegerField()),
                ('fuel_type', models.CharField(max_length=20)),
                ('transmission', models.CharField(max_length=20)),
                ('km_driven', models.PositiveIntegerField()),
                ('colour', models.CharField(max_length=30)),
                ('owner_count', models.PositiveSmallIntegerField(default=1)),
                ('inspection_score', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('listing_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hub', models.CharField(max_length=64)),
                ('rc_transfer_status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('APPLIED', 'Applied at RTO'), ('IN_PROGRESS', 'In progress at RTO'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected by RTO')], default='NOT_STARTED', max_length=20)),
                ('rc_transfer_applied_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vehicles',
                'indexes': [models.Index(fields=['make', 'model'], name='vehicles_make_17021f_idx')],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='operations.vehicle'),
        ),
        migrations.CreateModel(
            name='OrderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('AADHAAR', 'Aadhaar'), ('PAN', 'PAN card'), ('ADDRESS_PROOF', 'Address proof'), ('DRIVING_LICENCE', 'Driving licence'), ('RC', 'Registration certificate'), ('INSURANCE', 'Insurance policy'), ('NOC', 'Loan NOC / hypothecation removal'), ('FORM_29_30', 'Form 29 / 30'), ('BANK_STATEMENT', 'Bank statement'), ('SALARY_SLIP', 'Salary slip')], max_length=24)),
                ('status', models.CharField(choices=[('NOT_UPLOADED', 'Not uploaded'), ('UPLOADED', 'Uploaded, awaiting verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='NOT_UPLOADED', max_length=20)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='operations.order')),
            ],
            options={
                'db_table': 'order_documents',
                'indexes': [models.Index(fields=['order', 'status'], name='order_docum_order_i_4921a9_idx')],
                'constraints': [models.UniqueConstraint(fields=('order', 'doc_type'), name='uniq_order_doc_type')],
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('event_type', models.CharField(db_index=True, max_length=48)),
                ('description', models.CharField(max_length=300)),
                ('actor_type', models.CharField(choices=[('SYSTEM', 'System'), ('AGENT', 'Operations agent'), ('CUSTOMER', 'Customer'), ('PARTNER', 'Partner / vendor')], default='SYSTEM', max_length=16)),
                ('actor_name', models.CharField(blank=True, max_length=80)),
                ('from_status', models.CharField(blank=True, max_length=32)),
                ('to_status', models.CharField(blank=True, max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='operations.order')),
            ],
            options={
                'db_table': 'order_events',
                'ordering': ['order_id', 'sequence'],
                'indexes': [models.Index(fields=['order', '-occurred_at'], name='order_event_order_i_1c6c83_idx')],
                'constraints': [models.UniqueConstraint(fields=('order', 'sequence'), name='uniq_order_event_sequence')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending at bank'), ('AUTHORIZED', 'Authorized, not captured'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, max_length=16)),
                ('method', models.CharField(choices=[('UPI', 'UPI'), ('NETBANKING', 'Net banking'), ('CARD', 'Debit/credit card'), ('CASH', 'Cash at hub'), ('CHEQUE', 'Cheque'), ('LOAN_DISBURSEMENT', 'Loan disbursement'), ('WALLET', 'Wallet')], max_length=24)),
                ('purpose', models.CharField(choices=[('TOKEN', 'Token / booking amount'), ('DOWN_PAYMENT', 'Down payment'), ('FULL_PAYMENT', 'Full vehicle payment'), ('LOAN_DISBURSEMENT', 'Loan disbursement'), ('CHARGES', 'RC transfer / service charges'), ('REFUND', 'Refund to customer')], max_length=24)),
                ('gateway', models.CharField(blank=True, max_length=40)),
                ('gateway_txn_id', models.CharField(blank=True, max_length=64)),
                ('failure_code', models.CharField(blank=True, max_length=40)),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
                ('initiated_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='operations.order')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-initiated_at'],
                'indexes': [models.Index(fields=['order', '-initiated_at'], name='payments_order_i_e1ff66_idx'), models.Index(fields=['status', '-initiated_at'], name='payments_status_eb525b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='orders_status_f8c8df_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-created_at'], name='orders_custome_12b615_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['hub', 'status'], name='orders_hub_f7ada8_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['expected_delivery_date'], name='orders_expecte_4311c5_idx'),
        ),
    ]
